name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: '00 01 * * *'

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    env:
      AGENT_OS: ${{ matrix.os }}
      RUST_TOOLCHAIN: ${{ matrix.rust }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          # This is the minimum supported Rust version of this crate.
          # When updating this, the reminder to update the minimum supported
          # Rust version in README.md.
          - 1.36.0
          - stable
          - nightly
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        shell: bash
        run: |
          . ./ci/install-rust.sh
      - name: cargo test
        run: |
          cargo test
      - name: cargo hack
        run: |
          cargo run -- hack check --each-feature --no-dev-deps

  style:
    name: style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - clippy
          - rustfmt
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        shell: bash
        run: |
          . ./ci/install-rust.sh
      - name: Install component
        shell: bash
        run: |
          . ./ci/install-component.sh ${{ matrix.component }}
      - name: cargo clippy
        if: matrix.component == 'clippy'
        run: |
          cargo clippy --all --all-features
      - name: cargo fmt -- --check
        if: matrix.component == 'rustfmt'
        run: |
          cargo fmt --all -- --check
